# Generated by Django 4.1.1 on 2022-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
